### ISSUE TITLE
Mouse module issues

### ISSUE THREAD

**Issue by marcusva** [py-sdl/py-sdl2#10]
Originally reported by: **sp4ztique (Bitbucket: [sp4ztique](https://bitbucket.org/sp4ztique), GitHub: [sp4ztique](https://github.com/sp4ztique))**

----------------------------------------

The mouse related functions i.e. SDL_GetMouseState(), aren't well documented for python, as in C they involve getting the mouse position via x and y pointers passed to the function, rather than just returning a tuple or using a class. I've had a lot of trouble getting this function to work, as I'm trying to use the mouse for unit movement, similar to diablo or RTS games, but even when I try and create pointers with ctypes, this function doesn't want to work. If I pass x and y as None, I can get it to return the mouse button states, but I can't seem to get the right ctypes pointer.

I'd really rather use this library than the dead pygame, but if I can't get the mouse co-ordinates I'm going to be forced to switch to pygame.

Also, sorry for posting this here, if you have somewhere you'd rather questions sent I'll happily switch to that platform.

----------------------------------------
- Bitbucket: https://bitbucket.org/marcusva/py-sdl2/issue/10

**Comment by a-hurst** [comment]
Since working with SDL2's mouse module is pretty unpleasant in Python, `sdl2.ext` would benefit a lot from having a simple `sdl2.ext.mouse` API. This would support getting/setting mouse position, showing/hiding the cursor, retrieving the button state, and (potentially) a function or two for checking for/handling mouse events in the SDL2 event queue.
