### ISSUE TITLE
Handling Resize of Images / Resize of Window with SpriteFactory/Renderer

### ISSUE THREAD

**Issue by JonBoyleCoding** [py-sdl/py-sdl2#233]
I recently created my first project with PySDL2 and I'm getting along ok so far. I was wondering how to handle the following cases:

- Load up an image using SpriteFactory and resize/scale to fit the window I've loaded up the image as follows

```python
# Create Sprite Factory
renderer = sdl2.ext.Renderer(window)
factory = sdl2.ext.SpriteFactory(sdl2.ext.TEXTURE, renderer=renderer)
sprite_renderer = factory.create_sprite_render_system(window)

# Load image
sprite = factory.from_image(str(current_image_path))

# Resize / Scale here???

# Render image
sprite_renderer.render(sprite)
```

- This also plays into how to deal with a window resizing I have the following in my events loop, but I don't know where to go from here. I want to ensure that the image scales to the window size, but other text I'm rendering stays the same size.

```python
if event.type == sdl2.SDL_WINDOWEVENT:
	if event.window.event == sdl2.SDL_WINDOWEVENT_RESIZED:
		w, h = event.window.data1, event.window.data2
```

Thanks in advance for any advice you can give to me

**Comment by JonBoyleCoding** [comment]
Just to add, I'm using:

- PySDL2 - 0.9.11
- pysdl2-dll - 2.0.20

**Comment by a-hurst** [comment]
Hey @JonBoyleCoding, for a new project I'd personally avoid using the SpriteFactory system and use the image functions from `sdl2.ext.image` instead: see `examples/transformations.py` and `examples/helloworld.py` for some worked examples of how to load manipulate, and render images.

The fastest way to resize your image along with the window size would be to convert it into a texture (as in those examples) and then resize it dynamically when rendering by setting a custom destination rectangle size when rendering it with renderer.copy() (see the docs [here](https://pysdl2.readthedocs.io/en/0.9.11/modules/ext/renderer.html#sdl2.ext.renderer.Renderer.copy)). Then, every loop when you draw the image, you can check the height and width of the window and adjust the `dstrect` rectangle accordingly. The nice part is that you don't need to do any slow resizing operations on the actual image, since the renderer takes care of it all on the GPU!

Hope that helps, and let me know if you have any other questions!

**Comment by JonBoyleCoding** [comment]
Ok great! Thanks for the response - I will try to refactor it this way.
